# this is the code to run the ESP32-s3 that controls the sensors and hardware
esphome:
  name: hydro-hardware
  friendly_name: Hydro-Hardware

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Myvb70vEvz+4bgUkZh/9NeJnf2EnkHsOrrJVRWrcVcI="

ota:
  - platform: esphome
    password: "2601860170cefaf50c8226d0c28dec29"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hydro-Hardware Fallback Hotspot"
    password: "XfpHzz3ZbRLI"

captive_portal:
# Creates the Web server to view current readings and status
web_server:
  port: 80
# Defines the i2c bus on the ESP32
i2c:
  sda: 7
  scl: 6
  scan: true
  frequency: 800khz
  timeout: 10ms
# Defines the One-Wire Bus on the ESP32
one_wire:
  - platform: gpio
    pin: 11
# Defines the indavidual sensors connected to the ESP32
sensor:
# The Humidity and Temperature sensor
  - platform: sht3xd
    temperature:
      name: "Air Temperature"
    humidity:
      name: "Air Humidity"
    address: 0x44
    update_interval: 10s
# The Water TDS Meter
  - platform: adc
    pin: GPIO1
    name: "Water TDS"
    update_interval: 10s
    unit_of_measurement: "ppm"
    filters:
      - lambda: return (((133.42*(x*(3.3/1024))*(x*(3.3/1024))*(x*(3.3/1024))) - (255.86*(x*(3.3/1024))*(x*(3.3/1024))) + (857.39*(x*(3.3/1024))))*0.5)*1000;
# The Light sensor
  - platform: tsl2591
    name: "Lux"
    id: "my_tls2591"
    address: 0x29
    update_interval: 10s
    gain: auto
    device_factor: 53
    glass_attenuation_factor: 14.4
    visible:
      name: "TSL2591 visible light"
    infrared:
      name: "TSL2591 infrared light"
    full_spectrum:
      name: "TSL2591 full spectrum light"
    calculated_lux:
      id: i_lux
      name: "TSL2591 Lux"
    actual_gain:
      id: "actual_gain"
      name: "TSL2591 actual gain"
# the Water Temperature sensor
  - platform: dallas_temp
    address: 0x5701192130951028
    name: "Water Temperature"
    update_interval: 1s
    filters: 
      - median:
          window_size: 10
          send_every: 10
          send_first_at: 10

  # The Currently nonfunctional PH Sensor
  - platform: adc
    attenuation: 11db
    raw: True
    pin: GPIO4
    id: ph
    name: "pH Sensor"
    update_interval: 1s
    unit_of_measurement: pH
    filters:
      - median:
          window_size: 7
          send_every: 4
          send_first_at: 3
      
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
      - lambda: return x/4095 *14; 
# Defines the relay controlling the Waterpump
switch:
  - platform: gpio
    name: relay
    pin:
      number: GPIO35
